const readline = require("readline-sync");
// Sir only this function is generated by AI as i didn't knew how to make it more visible in terminal
function printSolutionMatrix(matrix) {
	const cellWidth = 12;
	const emptyCell = " ".repeat(cellWidth);

	const rowSeparator = "-".repeat(matrix[0].length * (cellWidth + 3));

	for (let row of matrix) {
		console.log(
			row
				.map((cell) =>
					cell === null
						? emptyCell
						: cell.toString().padStart(cellWidth)
				)
				.join(" | ")
		);
		console.log(rowSeparator);
	}
}

function printMatrix(map) {
	let line = "    ";
	for (let i = 0; i < gridSize; i++) {
		line += i + "  ";
	}
	console.log(line);

	for (let i = 0; i < gridSize; i++) {
		let line = "";
		line += i + " | ";
		for (let j = 0; j < gridSize; j++) {
			let obj = map.get(`${i},${j}`);
			line += obj.color.toUpperCase()[0];
			if (obj.haveQueen) {
				line += "#";
			} else {
				line += " ";
			}
			line += " ";
		}
		console.log("____________________________");
		console.log(line);
	}
	console.log("____________________________");
}

function checkValidityOfCell(obj, loc, region, row, column, edge) {
	return (
		region.includes(obj.color) ||
		row.includes(loc[0]) ||
		column.includes(loc[2]) ||
		edge.includes(loc)
	);
}

function checkEdgeValidity(edges, loc) {
	return edges.includes(loc);
}

function updateValidity(obj, loc, region, row, column, edge) {
	region.push(obj.color);
	row.push(loc[0]);
	column.push(loc[2]);

	let arr = [
		[loc[0] - 1, loc[2] - 1],
		[loc[0] - 1, parseInt(loc[2]) + 1],
		[parseInt(loc[0]) + 1, loc[2] - 1],
		[parseInt(loc[0]) + 1, parseInt(loc[2]) + 1],
	];

	for ([x, y] of arr) {
		if (x != -1 && x != gridSize && y != -1 && y != gridSize) {
			edge.push(`${x},${y}`);
		}
	}
}

function updateEdgeValidity(markedEdges, row, col) {
	let arr = [
		[row + 1, col + 1],
		[row - 1, col + 1],
	];

	for (let [x, y] of arr) {
		if (x != -1 && x != gridSize && y != -1 && y != gridSize) {
			markedEdges.push(`${x},${y}`);
		}
	}
	console.log(markedEdges)
}

function askQuestionsTillTrue(map, region, row, column, edge) {
	let obj;
	let loc;
	while (true) {
		if (!loc) {
			loc = readline.question("Enter location in form of i,j : ");
		} else {
			loc = readline.question("Wrong !!! Try Again : ");
		}
		obj = map.get(loc);
		if (!checkValidityOfCell(obj, loc, region, row, column, edge)) {
			break;
		}
	}
	return { obj, loc };
}

function makeNullMatrix() {
	let matrix = [];
	for (let i = 0; i < gridSize; i++) {
		let arr = [];
		for (let j = 0; j < gridSize; j++) {
			arr.push(null);
		}
		matrix.push(arr);
	}
	return matrix;
}

function indexFromPosition(num) {
	return [Math.floor(num / gridSize), num % gridSize];
}

function addColorFromBoundry(matrix, cell) {
	let [row, col] = indexFromPosition(cell, gridSize);
	let boundries = [
		[row - 1, col],
		[row, col + 1],
		[row + 1, col],
		[row, col - 1],
	];

	let tempColor = [];
	for ([x, y] of boundries) {
		if (
			x >= 0 &&
			x < gridSize &&
			y >= 0 &&
			y < gridSize &&
			matrix[x][y] != null
		) {
			tempColor.push(matrix[x][y]);
		}
	}
	if (tempColor.length != 0) {
		matrix[row][col] =
			tempColor[Math.floor(Math.random() * tempColor.length)];
		return true;
	} else {
		return false;
	}
}

function generateRandomSolutionWithoutRegions(
	matrix,
	availableRows,
	markedEdges,
	colors
) {
	for (let col = 0; col < gridSize; col++) {
		let row;
		let attempts = 0
		while (true) {
			if(attempts ==10){
				console.log("returning false")
				return false
			}
			index = Math.floor(Math.random() * availableRows.length);
			row = availableRows[index];
			loc = `${row},${col}`;
			if (!checkEdgeValidity(markedEdges, loc)) {
				console.log(loc)
				console.log(availableRows)
				availableRows.splice(index, 1);
				updateEdgeValidity(markedEdges, row, col);
				break;
			}
			attempts++
		}
		console.log(row , col)
		matrix[row][col] = colors.pop();
	}
	return true
}

function insertRegions(matrix, availablePosition) {
	while (availablePosition.length > 0) {
		let cellIndex = Math.floor(Math.random() * availablePosition.length);
		let cell = availablePosition[cellIndex];
		let [cellRow, cellCol] = indexFromPosition(cell);
		if (matrix[cellRow][cellCol] != null) {
			availablePosition.splice(cellIndex, 1);
			continue;
		}
		if (addColorFromBoundry(matrix, cell)) {
			availablePosition.splice(cellIndex, 1);
		}
	}
}

function getRandomBoard() {
	let matrix;
	let availablePosition;
	while(true){
		matrix = makeNullMatrix();
		let availableRows = [];
		for (let i = 0; i < gridSize; i++) {
			availableRows.push(i);
		}
	
		let markedEdges = [];
		availablePosition = [];
		let colors = [
			"green",
			"blue",
			"red",
			"white",
			"yellow",
			"purple",
			"navy",
			"silver",
			"magenta",
		];
		for (let i = 0; i < gridSize * gridSize; i++) {
			availablePosition.push(i);
		}
		if(generateRandomSolutionWithoutRegions(
			matrix,
			availableRows,
			markedEdges,
			colors
		)){
			break
		}
	}
	
	console.log("SOLUTION FOR THIS RANDOM PUZZLE");
	printSolutionMatrix(matrix);

	insertRegions(matrix, availablePosition);
	return matrix;
}

function makeBoard() {
	const map = new Map();
	let colors = getRandomBoard();

	for (let i = 0; i < gridSize; i++) {
		for (let j = 0; j < gridSize; j++) {
			map.set(`${i},${j}`, { color: colors[i][j], haveQueen: false });
		}
	}
	return map;
}

function startGame() {
	let regionOccupied = [];
	let rowOccupied = [];
	let columnOccupied = [];
	let edgeOccupied = [];
	while (true) {
		gridSize = parseInt(
			readline.question("Please enter grid size between 5 to 9 : ")
		);
		if (gridSize >= 5 && gridSize <= 9) {
			break;
		}
	}
	const map = makeBoard();

	printMatrix(map);
	for (let i = 0; i < gridSize; i++) {
		let { obj, loc } = askQuestionsTillTrue(
			map,
			regionOccupied,
			rowOccupied,
			columnOccupied,
			edgeOccupied
		);
		updateValidity(
			obj,
			loc,
			regionOccupied,
			rowOccupied,
			columnOccupied,
			edgeOccupied
		);
		map.set(loc, { ...obj, haveQueen: true });

		printMatrix(map);
	}
	console.log("You are correct");
}
let gridSize;
startGame();
// findSolution();
